### ISSUE TITLE
Exception on start with Debian testing

### ISSUE THREAD

**Issue by aog2000a** [ktgw0316/LightZone#283]
Steps to reproduce:

- Install LightZone 4.2.4 on Debian Bookworm/testing from this URL:
[https://download.opensuse.org/repositories/home:/ktgw0316:/LightZone/Debian_Testing/amd64/lightzone_4.2.4-0obs1_amd64.deb](https://download.opensuse.org/repositories/home:/ktgw0316:/LightZone/Debian_Testing/amd64/lightzone_4.2.4-0obs1_amd64.deb)
- NOTE: the same happens with the Debian 10, Debian 11 or Debian Unstable packages
- Try to execute lightzone
- After the splashcreen, lightzone crashes with a ClassNotFound exception, printing this:

> $ lightzone
Starting LightZone version 4.2.4 ...
with options :
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Debian-1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Debian-1, mixed mode, sharing)
/usr/share/java/lightzone/*:/usr/share/java/*
This is LightZone 4.2.4
Running Java version 17.0.6 (amd64)
Verifying Libraries
Initializing Engine Utilities
Max Memory:     2048 MB
Total Memory:     32 MB
Running on 16 processors
Tile Cache:     1024 MB
Allocating 7493 MB for the image cache.
Loading Classes
Scanning Color Profiles
Restoring Preferences
Starting Logging
Scanning Saved Documents
Opening...
Light Crafts JAI Library - 02/05/07
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: jiconfont/icons/FontAwesome
        at com.lightcrafts.ui.toolkit.IconFontFactory.<clinit>(IconFontFactory.java:62)
        at com.lightcrafts.ui.operation.OpActions.getImage(OpActions.java:239)
        at com.lightcrafts.ui.operation.OpActions.createStaticAddActions(OpActions.java:180)
        at com.lightcrafts.ui.operation.OpStack.getStaticAddActions(OpStack.java:152)
        at com.lightcrafts.ui.editor.OpsToolbar.<init>(OpsToolbar.java:30)
        at com.lightcrafts.ui.editor.ToolsContainer.<init>(ToolsContainer.java:24)
        at com.lightcrafts.ui.editor.PreviewSplit.<init>(PreviewSplit.java:48)
        at com.lightcrafts.ui.editor.EditorControls.<init>(EditorControls.java:58)
        at com.lightcrafts.ui.editor.Editor.<init>(Editor.java:406)
        at com.lightcrafts.ui.editor.DisabledEditor.<init>(DisabledEditor.java:30)
        at com.lightcrafts.ui.editor.Document.createDisabledEditor(Document.java:374)
        at com.lightcrafts.app.ComboFrame.<init>(ComboFrame.java:175)
        at com.lightcrafts.app.Application.createNewComboFrame(Application.java:1499)
        at com.lightcrafts.app.Application.openEmpty(Application.java:571)
        at com.lightcrafts.app.Application$11.run(Application.java:2227)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: jiconfont.icons.FontAwesome
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 28 more

**Comment by jedd** [comment]
Can confirm this is breaking on Debian sid.

This might be related:  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1011165#46 
 ... possibly, for a different package that was also affected by some changes to libjiconfont-font-awesome-java package in Debian.

fyi  `dpkg -L libjiconfont-font-awesome-java`

```
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libjiconfont-font-awesome-java
/usr/share/doc/libjiconfont-font-awesome-java/changelog.Debian.gz
/usr/share/doc/libjiconfont-font-awesome-java/copyright
/usr/share/java
/usr/share/java/jiconfont-font_awesome.jar
/usr/share/maven-repo
/usr/share/maven-repo/com
/usr/share/maven-repo/com/github
/usr/share/maven-repo/com/github/jiconfont
/usr/share/maven-repo/com/github/jiconfont/jiconfont-font_awesome
/usr/share/maven-repo/com/github/jiconfont/jiconfont-font_awesome/4.7.0.1
/usr/share/maven-repo/com/github/jiconfont/jiconfont-font_awesome/4.7.0.1/jiconfont-font_awesome-4.7.0.1.pom
/usr/share/maven-repo/com/github/jiconfont/jiconfont-font_awesome/debian
/usr/share/maven-repo/com/github/jiconfont/jiconfont-font_awesome/debian/jiconfont-font_awesome-debian.pom
/usr/share/java/jiconfont-font_awesome-4.7.0.1.jar
/usr/share/maven-repo/com/github/jiconfont/jiconfont-font_awesome/4.7.0.1/jiconfont-font_awesome-4.7.0.1.jar
/usr/share/maven-repo/com/github/jiconfont/jiconfont-font_awesome/debian/jiconfont-font_awesome-debian.jar
```

and if helpful:

```
jarre:~# dpkg -l | grep -i awesome
ii  fonts-font-awesome                               5.0.10+really4.7.0~dfsg-4.1               all          iconic font designed for use with Twitter Bootstrap
ii  libfontawesomefx-java                            9.1.2-3                                   all          Font Awesome perfectly integrated into JavaFX
ii  libjiconfont-font-awesome-java                   4.7.0.1-1                                 all          jIconFont - Font Awesome
```

**Comment by ktgw0316** [comment]
Hi, I updated the debian packages today. You can download it from [OBS](https://software.opensuse.org//download.html?project=home%3Aktgw0316%3ALightZone&package=lightzone) as always. Please try it and let me know if it works.

Thank you @jedd for the related bug info, it was very helpful for me. Yes, the jiconfont-fontawesome broke its API compatibility between 4.7.0.0 and 4.7.0.1.

**Comment by jedd** [comment]
Thanks @ktgw0316  -- unfortunately looks like the deb package build missed a few files.  I checked the 3 architectures for unstable & testing on Debian from the Grab Binary Packages Directly, after the repo -> apt-get was showing the same problem -- 1.9 kB for the deb, 11 MB for the rpm:

```
jarre:/home/jedd/Downloads# ls -lh lightzone_4.2.4-1_amd64.deb
-rw-r--r-- 1 jedd jedd 1.9K Mar 19 11:01 lightzone_4.2.4-1_amd64.deb

jarre:/home/jedd/Downloads# ls -lh lightzone-4.2.4-170.49.x86_64.rpm 
-rw-r--r-- 1 jedd jedd 11M Mar 19 11:02 lightzone-4.2.4-170.49.x86_64.rpm

jarre:/home/jedd/Downloads# dpkg --contents lightzone_4.2.4-1_amd64.deb 
drwxr-xr-x root/root         0 2023-03-19 00:30 ./
drwxr-xr-x root/root         0 2023-03-19 00:30 ./usr/
drwxr-xr-x root/root         0 2023-03-19 00:30 ./usr/share/
drwxr-xr-x root/root         0 2023-03-19 00:30 ./usr/share/doc/
drwxr-xr-x root/root         0 2023-03-19 00:30 ./usr/share/doc/lightzone/
-rw-r--r-- root/root       456 2023-03-19 00:30 ./usr/share/doc/lightzone/changelog.Debian.gz

jarre:/home/jedd/Downloads# 

```

**Comment by aog2000a** [comment]
> Hi, I updated the debian packages today. You can download it from [OBS](https://software.opensuse.org//download.html?project=home%3Aktgw0316%3ALightZone&package=lightzone) as always. Please try it and let me know if it works.
> 

As @jedd says the Debian packages are (almost) empty, but i will try again as soon as you can rebuild. Thanks a lot in any case @ktgw0316 !

**Comment by ktgw0316** [comment]
After struggling with the Open Build Service, I think I could build a decent package (version 4.2.4-1+197.1).  The package size is 8.8 MB now, and the output of `dpkg --contents` looks good.

@jedd @aog2000a Could you test it again?

**Comment by aog2000a** [comment]
@ktgw0316 @jedd yesterday i installed your package version 4.2.4-1+196.1 and it starts perfectly fine. I will update and try the latest version 196.2, anything special which was still broken/ resp. to test?

**Comment by jedd** [comment]
Apologies, should have confirmed too that it runs fine on Debian sid on amd64 arch here -- the closed ticket suggested some (well placed :) degree of optimism!

**Comment by aog2000a** [comment]
I just tried the new **4.2.4-1+197.1**, also works fine :-)
Thank you very much to you both.

**Comment by ktgw0316** [comment]
Thanks!  When I tested 4.2.4-1+196.1, it couldn't be installed on Debian bookworm (testing) and sid (unstable) because of lack of libtiff5 package. So I added the libtiff6 in dependency list for 4.2.4-1+197.1.

**Comment by aog2000a** [comment]
@ktgw0316 oh, sorry my bad, forgot to mention it: i had compiled libtiff5 from an older Debian release to allow installing LightZone, good to know i could remove that package now :)
