### ISSUE TITLE
Ubuntu 23.04 LightZone version 5.0.0 beta1 not starting

### ISSUE THREAD

**Issue by nanoav** [ktgw0316/LightZone#309]
Ubuntu 23.04 LightZone version 5.0.0 beta1 not starting.

Fresh install

Starting LightZone version 5.0.0 beta1 ...
with options :
java version "19.0.1" 2022-10-18
Java(TM) SE Runtime Environment (build 19.0.1+10-21)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)
/usr/share/java/lightzone/*:/usr/share/java/*
This is LightZone 5.0.0~beta1
Running Java version 19.0.1 (amd64)
java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/spi/ImageReaderSpiBase
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:495)
	at java.base/java.lang.Class.forName(Class.java:474)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1217)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at java.desktop/javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:185)
	at java.desktop/javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:113)
	at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:134)
	at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:64)
	at com.lightcrafts.splash.SplashImage.backgroundImage(SplashImage.java:74)
	at com.lightcrafts.splash.SplashImage.<init>(SplashImage.java:29)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:39)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)
Caused by: java.lang.ClassNotFoundException: com.twelvemonkeys.imageio.spi.ImageReaderSpiBase
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 25 more
![image](https://github.com/ktgw0316/LightZone/assets/91558318/d018e0d3-cf2a-4d27-a69a-9f9e705972b3)
![Screenshot from 2023-09-02 22-15-10](https://github.com/ktgw0316/LightZone/assets/91558318/d62899b8-ec5a-4b62-a069-7a2b816af17c)

**Comment by sfink16** [comment]
I'm running on Ubuntu 22.04 and my LZ opens with a different Java, but opens/works.  Here's the beginning of my run:

_openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
/usr/share/java/lightzone/*:/usr/share/java/*
This is LightZone 5.0.0~beta1
Running Java version 11.0.20.1 (amd64)_

**Comment by nanoav** [comment]
For me in Ubuntu  22.04 LightZone worked too. Downgraded system twice, only to have passibility to use LightZone, but each time I upgrade to Ubuntu 23.04,  LightZone stopped working.

**Comment by sfink16** [comment]
> For me in Ubuntu 22.04 LightZone worked too. Downgraded system twice, only to have passibility to use LightZone, but each time I upgrade to Ubuntu 23.04, LightZone stopped working.

Going into Synaptic Package Manager, I entered JDK and found the package OpenJDK-11-JRE installed.  Also, the Headless package is installed.  Perhaps you can find that and install it.

**Comment by nanoav** [comment]
$ lightzone
Starting LightZone version 5.0.0 beta1 ...
with options :
java version "11.0.20" 2023-07-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.20+9-LTS-256)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.20+9-LTS-256, mixed mode)
/usr/share/java/lightzone/*:/usr/share/java/*
This is LightZone 5.0.0~beta1
Running Java version 11.0.20 (amd64)
java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/spi/ImageReaderSpiBase
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1210)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at java.desktop/javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:184)
	at java.desktop/javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:113)
	at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:134)
	at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at com.lightcrafts.splash.SplashImage.backgroundImage(SplashImage.java:74)
	at com.lightcrafts.splash.SplashImage.<init>(SplashImage.java:29)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:39)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)
Caused by: java.lang.ClassNotFoundException: com.twelvemonkeys.imageio.spi.ImageReaderSpiBase
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 24 more

**Comment by sfink16** [comment]
> $ lightzone Starting LightZone version 5.0.0 beta1 ... with options : java version "11.0.20" 2023-07-18 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.20+9-LTS-256) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.20+9-LTS-256, mixed mode) /usr/share/java/lightzone/_:/usr/share/java/_ This is LightZone 5.0.0~beta1 Running Java version 11.0.20 (amd64) java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/spi/ImageReaderSpiBase at java.base/java.lang.ClassLoader.defineClass1(Native Method) at 

Your version is different than mine.  Openjdk is what you want.  You don't have an OpenJDK option?  Mine was found in the Synaptic app, by searching for JDK.  Here's mine, which opens with no EXIF errors due to no EXIF data in the conversion prior to LZ:
$ lightzone
Starting LightZone version 5.0.0 beta1 ...
with options :
openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
/usr/share/java/lightzone/*:/usr/share/java/*
This is LightZone 5.0.0~beta1
Running Java version 11.0.20.1 (amd64)
Verifying Libraries
Initializing Engine Utilities
Max Memory:     2048 MB
Total Memory:    250 MB
Running on 4 processors
Tile Cache:     1024 MB
Allocating 5833 MB for the image cache.
Malformed display profile at (sRGB default)
Loading Classes
Scanning Color Profiles
Restoring Preferences
Starting Logging
Scanning Saved Documents
Opening...
Light Crafts JAI Library - 02/05/07
Sep 06, 2023 2:38:26 PM com.lightcrafts.image.metadata.ImageMetadataReader logException
INFO: com.lightcrafts.image.metadata.BadImageMetadataException: /media/steve/9630-E17B/100EOSR7/W5A2126.dng
Sep 06, 2023 2:38:26 PM com.lightcrafts.image.metadata.ImageMetadataReader logException
INFO: com.lightcrafts.image.metadata.BadImageMetadataException: /media/steve/9630-E17B/100EOSR7/W5A2126.dng
Sep 06, 2023 2:38:26 PM com.lightcrafts.image.metadata.ImageMetadataReader logException
INFO: com.lightcrafts.image.metadata.BadImageMetadataException: /media/steve/9630-E17B/100EOSR7/W5A2126.dng
Sep 06, 2023 2:38:26 PM com.lightcrafts.image.metadata.ImageMetadataReader logException
INFO: com.lightcrafts.image.metadata.BadImageMetadataException: /media/steve/9630-E17B/100EOSR7/W5A2126.dng
Sep 06, 2023 2:38:26 PM com.lightcrafts.image.metadata.ImageMetadataReader logException
INFO: com.lightcrafts.image.metadata.BadImageMetadataException: /media/steve/9630-E17B/100EOSR7/W5A2126.dng
Sep 06, 2023 2:39:06 PM com.lightcrafts.image.metadata.ImageMetadataReader logException
INFO: com.lightcrafts.image.metadata.BadImageMetadataException: /media/steve/9630-E17B/100EOSR7/W5A2126.dng
Sep 06, 2023 2:39:06 PM com.lightcrafts.image.metadata.ImageMetadataReader logException
INFO: com.lightcrafts.image.metadata.BadImageMetadataException: /media/steve/9630-E17B/100EOSR7/W5A2126.dng

**Comment by nanoav** [comment]
I purged all java versions, Lightzone packed (or requested JDk 17),
installded, all the same.
Changed to ubuntu JDK 11:
 lightzone
Starting LightZone version 5.0.0 beta1 ...
with options :
openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu123.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu123.04,
mixed mode, sharing)
/usr/share/java/lightzone/*:/usr/share/java/*
This is LightZone 5.0.0~beta1
Running Java version 11.0.20.1 (amd64)
java.lang.NoClassDefFoundError:
com/twelvemonkeys/imageio/spi/ImageReaderSpiBase
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1022)
at
java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
at
java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
at
java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
at
java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
a

**Comment by sfink16** [comment]
> This is LightZone 5.0.0~beta1
> Running Java version 11.0.20.1 (amd64)
> java.lang.NoClassDefFoundError:
> com/twelvemonkeys/imageio/spi/ImageReaderSpiBase
> at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1022
> com/twelvemonkeys/imageio/spi/ImageReaderSpiBase

That's above my pay grade range.  Here's what I found:
https://www.tabnine.com/code/java/classes/com.twelvemonkeys.imageio.spi.ImageWriterSpiBase

**Comment by nanoav** [comment]
Thank you for the answer and link, I am really appreciate.

**Comment by ktgw0316** [comment]
@nanoav The `com.twelvemonkeys.imageio.spi.ImageReaderSpiBase` class is provided by `/usr/share/java/imageio-core.jar` in [libtwelvemonkeys-java](https://packages.ubuntu.com/lunar/all/libtwelvemonkeys-java/filelist) package on Ubuntu and Debian.  Would you try (re-) install that package?

By the way, LightZone doesn't use the twelvemonkeys-imageio, so I have no idea why that error occurs.

**Comment by nanoav** [comment]
Thank you very much, I'll try to (re) install it.

**Comment by nanoav** [comment]
Thank you for your help.
After installing  libtwelvemonkeys-java
<https://packages.ubuntu.com/lunar/all/libtwelvemonkeys-java/filelist>
lightzone started as usual.

**Comment by nanoav** [comment]
Thank you for your help.
After installing  libtwelvemonkeys-java
<https://packages.ubuntu.com/lunar/all/libtwelvemonkeys-java/filelist>
lightzone started as usual.
