### ISSUE TITLE
LightZone 5.0.0 beta-2 failing to launch with endless loop - Debian unstable

### ISSUE THREAD

**Issue by jedd** [ktgw0316/LightZone#331]
**Describe the bug**
Launching 5.0.0 (beta-1, then beta-2) on Debian unstable (sid) throws up the splash screen, then has some timeouts, and then goes into an endless loop of JAVA output oscillating between TIMED_WAITING & RUNNABLE (excerpt included below).

I'm troubleshooting now - but this may be a known problem / easy fix.

**To Reproduce**
Run lightzone, without parameters, from CLI.

**Expected behavior**
Normal / successful launch

**Desktop (please complete the following information):**
Debian unstable (sid) release 
Xeon with 32GB RAM.
Three releases of OpenJDK present, but LightZone is definitely picking up version 18 (refer screen output below)

```
jedd@jarre:~$ dpkg -l | grep openjdk
ii  openjdk-11-jre:amd64                                     11.0.21+9-1                               amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-11-jre-headless:amd64                            11.0.21+9-1                               amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  openjdk-17-jre:amd64                                     17.0.9+9-2                                amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-17-jre-headless:amd64                            17.0.9+9-2                                amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  openjdk-18-jre:amd64                                     18.0.2+9-2                                amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-18-jre-headless:amd64                            18.0.2+9-2                                amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
jedd@jarre:~$ dpkg -l | grep lightzone
ii  lightzone                                                5.0.0.beta2-1+210.77                      amd64        Open-source professional-level digital darkroom software
```

**Screenshots**

Screen output running from CLI:

```
jedd@jarre:~$ lightzone 
Starting LightZone version 5.0.0 beta2 ...
with options :
openjdk version "18.0.2-ea" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2-ea+9-Debian-2)
OpenJDK 64-Bit Server VM (build 18.0.2-ea+9-Debian-2, mixed mode, sharing)
/usr/share/java/lightzone/*:/usr/share/java/*
This is LightZone 5.0.0~beta2
Running Java version 18.0.2-ea (amd64)
Verifying Libraries
Initializing Engine Utilities
Max Memory:     2048 MB
Total Memory:    504 MB
Running on 8 processors
Tile Cache:     1024 MB
Allocating 7564 MB for the image cache.
Malformed display profile at (sRGB default)
Loading Classes
Scanning Color Profiles
Restoring Preferences
Starting Logging
Scanning Saved Documents
Opening...
EventThread blocked for 2.000 seconds
EventThread blocked for 4.001 seconds
EventThread blocked for 6.002 seconds
EventThread blocked for 8.002 seconds
EventThread blocked for 10.002 seconds
EventThread blocked for 12.002 seconds
EventThread blocked for 14.003 seconds
EventThread blocked for 16.003 seconds
AWT-XAWT: RUNNABLE
        at java.desktop@18.0.2-ea/sun.awt.X11.XToolkit.waitForEvents(Native Method)
        at java.desktop@18.0.2-ea/sun.awt.X11.XToolkit.run(XToolkit.java:681)
        at java.desktop@18.0.2-ea/sun.awt.X11.XToolkit.run(XToolkit.java:645)
        at java.base@18.0.2-ea/java.lang.Thread.run(Thread.java:833)
TileReaper: WAITING
        at java.base@18.0.2-ea/java.lang.Object.wait(Native Method)
        at java.base@18.0.2-ea/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
        at java.base@18.0.2-ea/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
        at app//com.lightcrafts.jai.utils.LCTileCache$TileReaper.run(LCTileCache.java:1002)
Finalizer: WAITING
        at java.base@18.0.2-ea/java.lang.Object.wait(Native Method)
        at java.base@18.0.2-ea/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
        at java.base@18.0.2-ea/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
        at java.base@18.0.2-ea/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:183)
Timer-0: TIMED_WAITING
        at java.base@18.0.2-ea/java.lang.Object.wait(Native Method)
        at java.base@18.0.2-ea/java.util.TimerThread.mainLoop(Timer.java:563)
        at java.base@18.0.2-ea/java.util.TimerThread.run(Timer.java:516)
FileSystemWatchService: RUNNABLE
        at java.base@18.0.2-ea/sun.nio.fs.LinuxWatchService.poll(Native Method)
        at java.base@18.0.2-ea/sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314)
        at java.base@18.0.2-ea/java.lang.Thread.run(Thread.java:833)
DirectoryMonitor.MonitorThread: WAITING
        at java.base@18.0.2-ea/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@18.0.2-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
        at java.base@18.0.2-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
        at java.base@18.0.2-ea/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3464)
        at java.base@18.0.2-ea/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3435)
        at java.base@18.0.2-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
        at java.base@18.0.2-ea/java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:485)
        at java.base@18.0.2-ea/java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:673)
        at java.base@18.0.2-ea/sun.nio.fs.AbstractWatchService.take(AbstractWatchService.java:118)
        at app//com.lightcrafts.utils.directory.DirectoryMonitor$MonitorThread.run(DirectoryMonitor.java:145)
```

**Comment by sfink16** [comment]
@jedd Have you tried version 17?  I think version 18 did not work well on my Ubunutu 22.04 desktop.

**Comment by jedd** [comment]
@sfink16 Good idea, and my apologies I forgot to update this last night, after discovering some other weirdness with a file system timing out on scan(eg 'df'), which might have been root cause of this problem above. 

File system in question was keybase's KBFS, which has not been an issue previously, and is not really maintained much anymore, but other Debian packages may now have some conflict with that suite.

Either way, LightZone launches fine for me now, so I'll close this ticket.
