### ISSUE TITLE
Lightzone fails to launch in Mint 22

### ISSUE THREAD

**Issue by becker44a** [ktgw0316/LightZone#344]
```
Testing Lightzone in Mint 22 64-bit Cinnamon, running in a Virtualbox VM (Ram:4G, CPUs: 4, Shell: bash)
Installed newly built PPA:  successful
Installed Lightzone from PPA:  successful  (dialog below)
Launch Lightzone:  Failed with exception  (dialog below)

=================================================================
Lightzone Installation (successful)
=================================================================
sudo apt-get install -y lightzone
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  cabextract libavcodec-extra libunshield0 unshield
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  javahelp2 junit4 junit5 libapiguardian-java libauto64fto32f-java
  libejml-java libgeronimo-annotation-1.3-spec-java libhamcrest-java
  libjetbrains-annotations-java libjiconfont-font-awesome-java
  libjiconfont-google-material-design-icons-java libjiconfont-java
  libjiconfont-swing-java libjsr305-java liblensfun-data-v1 liblensfun1
  liblombok-java libopenjson-java libopentest4j-java
  libopentest4j-reporting-java libpicocli-java libunivocity-parsers-java
  libxml2-utils
Suggested packages:
  javahelp2-doc libjetbrains-annotations-java-doc libjsr305-java-doc
The following NEW packages will be installed:
  javahelp2 junit4 junit5 libapiguardian-java libauto64fto32f-java
  libejml-java libgeronimo-annotation-1.3-spec-java libhamcrest-java
  libjetbrains-annotations-java libjiconfont-font-awesome-java
  libjiconfont-google-material-design-icons-java libjiconfont-java
  libjiconfont-swing-java libjsr305-java liblensfun-data-v1 liblensfun1
  liblombok-java libopenjson-java libopentest4j-java
  libopentest4j-reporting-java libpicocli-java libunivocity-parsers-java
  libxml2-utils lightzone
0 upgraded, 24 newly installed, 0 to remove and 169 not upgraded.
Need to get 18.8 MB of archives.
After this operation, 36.6 MB of additional disk space will be used.
Get:1 http://ubuntu.mirror.constant.com noble/universe amd64 javahelp2 all 2.0.05.ds1-10 [942 kB]
Get:2 http://ubuntu.mirror.constant.com noble/universe amd64 libhamcrest-java all 2.2-2 [117 kB]
Get:3 http://ubuntu.mirror.constant.com noble/universe amd64 junit4 all 4.13.2-4 [347 kB]
Get:4 http://ubuntu.mirror.constant.com noble/universe amd64 libapiguardian-java all 1.1.2-1 [4,598 B]
Get:5 http://ubuntu.mirror.constant.com noble/universe amd64 libopentest4j-java all 1.2.0-4 [9,396 B]
Get:6 http://ubuntu.mirror.constant.com noble/universe amd64 libopentest4j-reporting-java all 0.1.0-M1-2 [49.3 kB]
Get:7 http://ubuntu.mirror.constant.com noble/universe amd64 libpicocli-java all 4.6.2-2 [387 kB]
Get:8 http://ubuntu.mirror.constant.com noble/universe amd64 libunivocity-parsers-java all 2.9.1-1 [394 kB]
Get:9 http://ubuntu.mirror.constant.com noble/universe amd64 junit5 all 5.10.1-1 [2,446 kB]
Get:10 http://ubuntu.mirror.constant.com noble/universe amd64 libauto64fto32f-java all 2.1+ds-1 [14.2 kB]
Get:11 http://ubuntu.mirror.constant.com noble/universe amd64 libgeronimo-annotation-1.3-spec-java all 1.3-1 [11.2 kB]
Get:12 http://ubuntu.mirror.constant.com noble/universe amd64 libjetbrains-annotations-java all 23.0.0-2 [30.5 kB]
Get:13 http://ubuntu.mirror.constant.com noble/universe amd64 libjsr305-java all 0.1~+svn49-11 [27.0 kB]
Get:14 http://ubuntu.mirror.constant.com noble/universe amd64 liblombok-java all 1.18.24-2ubuntu1 [1,786 kB]
Get:15 http://ubuntu.mirror.constant.com noble/universe amd64 libejml-java all 0.41+ds-2 [2,490 kB]
Get:16 http://ubuntu.mirror.constant.com noble/universe amd64 libjiconfont-java all 1.0.0-2 [5,248 B]
Get:17 http://ubuntu.mirror.constant.com noble/universe amd64 libjiconfont-font-awesome-java all 4.7.0.1-1 [126 kB]
Get:18 http://ubuntu.mirror.constant.com noble/universe amd64 libjiconfont-swing-java all 1.0.1-2 [6,672 B]
Get:19 http://ubuntu.mirror.constant.com noble/universe amd64 liblensfun-data-v1 all 0.3.4-1build2 [338 kB]
Get:20 http://ubuntu.mirror.constant.com noble/universe amd64 liblensfun1 amd64 0.3.4-1build2 [54.5 kB]
Get:21 http://ubuntu.mirror.constant.com noble/universe amd64 libopenjson-java all 1.0.13-1 [27.8 kB]
Get:22 http://ubuntu.mirror.constant.com noble/main amd64 libxml2-utils amd64 2.9.14+dfsg-1.3ubuntu3 [39.4 kB]
Get:23 https://ppa.launchpadcontent.net/lightzone-team/lightzone/ubuntu noble/main amd64 libjiconfont-google-material-design-icons-java all 2.2.0.2-0~201812141610~ubuntu24.04.1 [94.1 kB]
Get:24 https://ppa.launchpadcontent.net/lightzone-team/lightzone/ubuntu noble/main amd64 lightzone amd64 5.0.0~beta2-0~202409040859~ubuntu24.04.1 [9,061 kB]
Fetched 18.8 MB in 22s (873 kB/s)
Selecting previously unselected package javahelp2.
(Reading database ... 477912 files and directories currently installed.)
Preparing to unpack .../00-javahelp2_2.0.05.ds1-10_all.deb ...
Unpacking javahelp2 (2.0.05.ds1-10) ...
Selecting previously unselected package libhamcrest-java.
Preparing to unpack .../01-libhamcrest-java_2.2-2_all.deb ...
Unpacking libhamcrest-java (2.2-2) ...
Selecting previously unselected package junit4.
Preparing to unpack .../02-junit4_4.13.2-4_all.deb ...
Unpacking junit4 (4.13.2-4) ...
Selecting previously unselected package libapiguardian-java.
Preparing to unpack .../03-libapiguardian-java_1.1.2-1_all.deb ...
Unpacking libapiguardian-java (1.1.2-1) ...
Selecting previously unselected package libopentest4j-java.
Preparing to unpack .../04-libopentest4j-java_1.2.0-4_all.deb ...
Unpacking libopentest4j-java (1.2.0-4) ...
Selecting previously unselected package libopentest4j-reporting-java.
Preparing to unpack .../05-libopentest4j-reporting-java_0.1.0-M1-2_all.deb ...
Unpacking libopentest4j-reporting-java (0.1.0-M1-2) ...
Selecting previously unselected package libpicocli-java.
Preparing to unpack .../06-libpicocli-java_4.6.2-2_all.deb ...
Unpacking libpicocli-java (4.6.2-2) ...
Selecting previously unselected package libunivocity-parsers-java.
Preparing to unpack .../07-libunivocity-parsers-java_2.9.1-1_all.deb ...
Unpacking libunivocity-parsers-java (2.9.1-1) ...
Selecting previously unselected package junit5.
Preparing to unpack .../08-junit5_5.10.1-1_all.deb ...
Unpacking junit5 (5.10.1-1) ...
Selecting previously unselected package libauto64fto32f-java.
Preparing to unpack .../09-libauto64fto32f-java_2.1+ds-1_all.deb ...
Unpacking libauto64fto32f-java (2.1+ds-1) ...
Selecting previously unselected package libgeronimo-annotation-1.3-spec-java.
Preparing to unpack .../10-libgeronimo-annotation-1.3-spec-java_1.3-1_all.deb ...
Unpacking libgeronimo-annotation-1.3-spec-java (1.3-1) ...
Selecting previously unselected package libjetbrains-annotations-java.
Preparing to unpack .../11-libjetbrains-annotations-java_23.0.0-2_all.deb ...
Unpacking libjetbrains-annotations-java (23.0.0-2) ...
Selecting previously unselected package libjsr305-java.
Preparing to unpack .../12-libjsr305-java_0.1~+svn49-11_all.deb ...
Unpacking libjsr305-java (0.1~+svn49-11) ...
Selecting previously unselected package liblombok-java.
Preparing to unpack .../13-liblombok-java_1.18.24-2ubuntu1_all.deb ...
Unpacking liblombok-java (1.18.24-2ubuntu1) ...
Selecting previously unselected package libejml-java.
Preparing to unpack .../14-libejml-java_0.41+ds-2_all.deb ...
Unpacking libejml-java (0.41+ds-2) ...
Selecting previously unselected package libjiconfont-java.
Preparing to unpack .../15-libjiconfont-java_1.0.0-2_all.deb ...
Unpacking libjiconfont-java (1.0.0-2) ...
Selecting previously unselected package libjiconfont-font-awesome-java.
Preparing to unpack .../16-libjiconfont-font-awesome-java_4.7.0.1-1_all.deb ...
Unpacking libjiconfont-font-awesome-java (4.7.0.1-1) ...
Selecting previously unselected package libjiconfont-google-material-design-icons-java.
Preparing to unpack .../17-libjiconfont-google-material-design-icons-java_2.2.0.2-0~201812141610~ubuntu24.04.1_all.deb ...
Unpacking libjiconfont-google-material-design-icons-java (2.2.0.2-0~201812141610~ubuntu24.04.1) ...
Selecting previously unselected package libjiconfont-swing-java.
Preparing to unpack .../18-libjiconfont-swing-java_1.0.1-2_all.deb ...
Unpacking libjiconfont-swing-java (1.0.1-2) ...
Selecting previously unselected package liblensfun-data-v1.
Preparing to unpack .../19-liblensfun-data-v1_0.3.4-1build2_all.deb ...
Unpacking liblensfun-data-v1 (0.3.4-1build2) ...
Selecting previously unselected package liblensfun1:amd64.
Preparing to unpack .../20-liblensfun1_0.3.4-1build2_amd64.deb ...
Unpacking liblensfun1:amd64 (0.3.4-1build2) ...
Selecting previously unselected package libopenjson-java.
Preparing to unpack .../21-libopenjson-java_1.0.13-1_all.deb ...
Unpacking libopenjson-java (1.0.13-1) ...
Selecting previously unselected package libxml2-utils.
Preparing to unpack .../22-libxml2-utils_2.9.14+dfsg-1.3ubuntu3_amd64.deb ...
Unpacking libxml2-utils (2.9.14+dfsg-1.3ubuntu3) ...
Selecting previously unselected package lightzone.
Preparing to unpack .../23-lightzone_5.0.0~beta2-0~202409040859~ubuntu24.04.1_amd64.deb ...
Unpacking lightzone (5.0.0~beta2-0~202409040859~ubuntu24.04.1) ...
Setting up libjetbrains-annotations-java (23.0.0-2) ...
Setting up libopentest4j-reporting-java (0.1.0-M1-2) ...
Setting up libjsr305-java (0.1~+svn49-11) ...
Setting up liblombok-java (1.18.24-2ubuntu1) ...
Setting up libpicocli-java (4.6.2-2) ...
Setting up liblensfun-data-v1 (0.3.4-1build2) ...
Setting up libjiconfont-java (1.0.0-2) ...
Setting up libunivocity-parsers-java (2.9.1-1) ...
Setting up libauto64fto32f-java (2.1+ds-1) ...
Setting up liblensfun1:amd64 (0.3.4-1build2) ...
Setting up libgeronimo-annotation-1.3-spec-java (1.3-1) ...
Setting up libapiguardian-java (1.1.2-1) ...
Setting up libjiconfont-swing-java (1.0.1-2) ...
Setting up javahelp2 (2.0.05.ds1-10) ...
Setting up libhamcrest-java (2.2-2) ...
Setting up libopenjson-java (1.0.13-1) ...
Setting up libopentest4j-java (1.2.0-4) ...
Setting up libjiconfont-google-material-design-icons-java (2.2.0.2-0~201812141610~ubuntu24.04.1) ...
Setting up libxml2-utils (2.9.14+dfsg-1.3ubuntu3) ...
Setting up junit4 (4.13.2-4) ...
Setting up libjiconfont-font-awesome-java (4.7.0.1-1) ...
Setting up junit5 (5.10.1-1) ...
Setting up libejml-java (0.41+ds-2) ...
Setting up lightzone (5.0.0~beta2-0~202409040859~ubuntu24.04.1) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for mate-menus (1.26.1+mint1) ...
Processing triggers for libc-bin (2.39-0ubuntu8.2) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
------------------------------------------------------------------------------------------------------------------

=================================================================
Launch Lightzone (failed - exception)
=================================================================
alan@lx22:~$ lightzone; echo -e xc:$?
Starting LightZone version 5.0.0 beta2 ...
with options :
openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu224.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu224.04, mixed mode, sharing)
/usr/share/java/lightzone/*:/usr/share/java/*
This is LightZone 5.0.0~beta2
Running Java version 21.0.4 (amd64)
Verifying Libraries
Initializing Engine Utilities
Max Memory:     2048 MB
Total Memory:     64 MB
Running on 4 processors
Tile Cache:     1024 MB
Allocating 0 MB for the image cache.
Loading Classes
Scanning Color Profiles
Restoring Preferences
Starting Logging
Scanning Saved Documents
Opening...
Light Crafts JAI Library - 02/05/07
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: jiconfont/icons/FontAwesome
	at com.lightcrafts.ui.toolkit.IconFontFactory.<clinit>(IconFontFactory.java:61)
	at com.lightcrafts.ui.operation.OpActions.getImage(OpActions.java:239)
	at com.lightcrafts.ui.operation.OpActions.createStaticAddActions(OpActions.java:180)
	at com.lightcrafts.ui.operation.OpStack.getStaticAddActions(OpStack.java:151)
	at com.lightcrafts.ui.editor.OpsToolbar.<init>(OpsToolbar.java:30)
	at com.lightcrafts.ui.editor.ToolsContainer.<init>(ToolsContainer.java:24)
	at com.lightcrafts.ui.editor.PreviewSplit.<init>(PreviewSplit.java:48)
	at com.lightcrafts.ui.editor.EditorControls.<init>(EditorControls.java:58)
	at com.lightcrafts.ui.editor.Editor.<init>(Editor.java:408)
	at com.lightcrafts.ui.editor.DisabledEditor.<init>(DisabledEditor.java:30)
	at com.lightcrafts.ui.editor.Document.createDisabledEditor(Document.java:373)
	at com.lightcrafts.app.ComboFrame.<init>(ComboFrame.java:175)
	at com.lightcrafts.app.Application.createNewComboFrame(Application.java:1494)
	at com.lightcrafts.app.Application.openEmpty(Application.java:571)
	at com.lightcrafts.app.Application$11.run(Application.java:2221)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: jiconfont.icons.FontAwesome
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 28 more
xc:0
------------------------------------------------------------------------------------------------------------------

It seems not to be able to find the class jiconfont.icons.FontAwesome, even though the package was listed as installed and set up.
If further testing would be helpful, let me know - happy to assist.
```

**Comment by ktgw0316** [comment]
@becker44a Thank you for the detailed info. It seems that jiconfont-font-awesome changed the package structure between 4.7.0.0 and 4.7.0.1.  I'll check if I can workaround this issue.

https://github.com/jIconFont/jiconfont-font_awesome/commit/932306879661d385455c30c550e0f8ecd03c1fc5

**Comment by ktgw0316** [comment]
@becker44a I updated the PPA packages today. Would you test it?

**Comment by texjoachim** [comment]
Just updated, Lightzone starts on Ubuntu Noble 24.04.01 LTS now.

**Comment by becker44a** [comment]
Just updated, Lightzone started w/ no issues on Mint 22 VM.  Launched successfully both from cli and gui menu.  Loaded some images - operation appears to be normal.
