### ISSUE TITLE
Lightzone doesn't start on Ubuntu Noble 24.04.1 LTS

### ISSUE THREAD

**Issue by dolfrudolf** [ktgw0316/LightZone#345]
**Describe the bug*
Lightzone crashes with the following error:

dolf@SmaltAsus:~$ lightzone 
Starting LightZone version 5.0.0 beta2 ...
with options :
openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu224.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu224.04, mixed mode, sharing)
/usr/share/java/lightzone/*:/usr/share/java/*
This is LightZone 5.0.0~beta2
Running Java version 21.0.4 (amd64)
Verifying Libraries
Initializing Engine Utilities
Max Memory:     2048 MB
Total Memory:    252 MB
Running on 8 processors
Tile Cache:     1024 MB
Allocating 2711 MB for the image cache.
Malformed display profile at (sRGB default)
Loading Classes
Scanning Color Profiles
Restoring Preferences
Starting Logging
Scanning Saved Documents
Opening...
Light Crafts JAI Library - 02/05/07
openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu224.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu224.04, mixed mode, sharing)
Malformed display profile at (sRGB default)
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: jiconfont/icons/FontAwesome
	at com.lightcrafts.ui.toolkit.IconFontFactory.<clinit>(IconFontFactory.java:61)
	at com.lightcrafts.ui.operation.OpActions.getImage(OpActions.java:239)
	at com.lightcrafts.ui.operation.OpActions.createStaticAddActions(OpActions.java:180)
	at com.lightcrafts.ui.operation.OpStack.getStaticAddActions(OpStack.java:151)
	at com.lightcrafts.ui.editor.OpsToolbar.<init>(OpsToolbar.java:30)
	at com.lightcrafts.ui.editor.ToolsContainer.<init>(ToolsContainer.java:24)
	at com.lightcrafts.ui.editor.PreviewSplit.<init>(PreviewSplit.java:48)
	at com.lightcrafts.ui.editor.EditorControls.<init>(EditorControls.java:58)
	at com.lightcrafts.ui.editor.Editor.<init>(Editor.java:408)
	at com.lightcrafts.ui.editor.DisabledEditor.<init>(DisabledEditor.java:30)
	at com.lightcrafts.ui.editor.Document.createDisabledEditor(Document.java:373)
	at com.lightcrafts.app.ComboFrame.<init>(ComboFrame.java:175)
	at com.lightcrafts.app.Application.createNewComboFrame(Application.java:1494)
	at com.lightcrafts.app.Application.openEmpty(Application.java:571)
	at com.lightcrafts.app.Application$11.run(Application.java:2221)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: jiconfont.icons.FontAwesome
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 28 more

**Desktop (please complete the following information):**4
dolf@SmaltAsus:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble

Thanks for help
 
Dolf

**Comment by ktgw0316** [comment]
@dolfrudolf I updated the PPA packages today.  Would you test it?

**Comment by ktgw0316** [comment]
(This issue is duplicate of #344 btw)

**Comment by texjoachim** [comment]
Just updated, Lightzone starts on Ubuntu Noble 24.04.01 LTS now.

**Comment by dolfrudolf** [comment]
Sorry, I have tested Lightzone only now. Program starts and some choices send him to the brick. For example I choose mask "Crisp" and the Lightzone becomes dead.

**Comment by dolfrudolf** [comment]
Sorry, I tested the Lightzone until today. The program starts but becomes dead during a few seconds. I am sending you messages from my terminal.

Thanks
[dump.txt](https://github.com/user-attachments/files/17307974/dump.txt)

**Comment by dolfrudolf** [comment]
I am sorry but my favorite program Lightzone still doesn't run on Ubuntu Noble 24.04_1 LTS. I am sending the copy of the terminal messages, file "a" is standard output and file "b" is 2> output.
Thanks for any advice
[a.txt](https://github.com/user-attachments/files/18300938/a.txt)
[b.txt](https://github.com/user-attachments/files/18300939/b.txt)
